# Generated by Django 5.1.6 on 2025-08-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_confirmaioncode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmaionCode',
            new_name='ConfirmationCode',
        ),
    ]
