# Generated by Django 5.1.6 on 2025-08-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_confirmaioncode_confirmationcode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
