# Generated by Django 5.1.6 on 2025-10-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_diaryentry_owner_diaryentry_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='picture',
        ),
    ]
